### ISSUE TITLE
Kinetic release

### ISSUE THREAD

**Issue by bmagyar** [ros-controls/control_msgs#17]
Hello folks,

ROS Kinetic is missing control_msgs for the final release. 
I volunteer to do the release but I'd like to have some +1-s before.

@adolfo-rt @davetcoleman @efernandez

**Comment by davetcoleman** [comment]
+1

**Comment by efernandez** [comment]
Thanks for volunteering! +1

BTW, are there any other packages that need attention for Kinetic?

**Comment by bmagyar** [comment]
I suppose the pending PR changes shouldn't be propagated back to indigo or jade, but only to kinetic, right @davetcoleman ?
I'm about to push the new devel branch.

**Comment by davetcoleman** [comment]
Makes sense to me to just keep it in Kinetic

**Comment by bmagyar** [comment]
:+1: Moving forward then, closing issue
