### ISSUE TITLE
ros2 bouncy?

### ISSUE THREAD

**Issue by AustinDeric** [ros-controls/control_msgs#22]
Has anyone attempted to convert this to ros2?  A bunch of the ros-industrial code depends on this great package and we are converting to ros2.

If not, i am going to go ahead and do that.

Thanks!

**Comment by bmagyar** [comment]
Thanks for getting in touch! I currently don't have the time to work on it but if you are willing to do the conversion, I can pull triggers on the release!

**Comment by nzlz** [comment]
Hi there, 

I'm having issues when I try to import the control_msgs module in python. Everything compiles just fine but in the end, I can't make use of the repo.

I asked about this first in ROS Answers and I have been told this could be an issue related with this repo, not my setup. Please take a look at [this reply](https://answers.ros.org/question/310623/cannot-import-module-control_msgs/?answer=310632#post-id-310632) and my question where I provide a few details.

**Comment by ipa-mdl** [comment]
The current CMakeLists.txt looks wrong, it seems to lack the `rosidl_generate_interfaces` call..

**Comment by ipa-mdl** [comment]
I have added an issue to track it: https://github.com/ros-controls/control_msgs/issues/25

**Comment by artivis** [comment]
@bmagyar I think this issue can be closed.

**Comment by ipa-mdl** [comment]
>  think this issue can be closed.

agreed
