### ISSUE TITLE
ROS2 Dashing

### ISSUE THREAD

**Issue by DavidMansolino** [ros-controls/control_msgs#33]
My package depends on control_msgs, I am trying to update my package to ROS2 Dashing, unfortunately, since `control_msgs` is not yet released for ROS2 Dashing I a quite stuck. Are you planning to create a release for Dashing?

**Comment by Pritish9** [comment]
I have made the ros-dashing changes so if a branch is created I can ask for a pull-request from       
   [here](https://github.com/seqsense/control_msgs/tree/dashing-devel)
