### ISSUE TITLE
ROS2 Eloquent Release

### ISSUE THREAD

**Issue by DavidMansolino** [ros-controls/control_msgs#37]
ROS2 Eloquent is going to be released very soon, it would be nice to make a new version of the `control_msgs` package supporting this version of ROS2 (there is probably nothing to change from the Dashing version).

**Comment by bmagyar** [comment]
Hot off the press
https://github.com/ros/rosdistro/pull/23170

**Comment by DavidMansolino** [comment]
Perfect, thank you!
