### ISSUE TITLE
ROS2 CI from ros2_control

### ISSUE THREAD

**Issue by matthew-reynolds** [ros-controls/control_msgs#42]
As with https://github.com/ros-controls/control_toolbox/issues/87, should setup CI for ROS2 branches 

The ROS2 branches are still running `kinetic-devel` CI, and then falsely succeeding without having actually tested on ROS2. The build status on the README is pretty misleading at the moment.

**Comment by bmagyar** [comment]
What do you mean exactly? These seems to be fine: https://travis-ci.org/github/ros-controls/control_msgs/jobs/617718997

**Comment by matthew-reynolds** [comment]
Whoops, you're definitely right... For some reason I was thinking the `crystal-devel` and `foxy-devel` branches were using the same `.travis.yml` as `kinetic-devel` (And therefore testing Kinetic/Lunar/Melodic). Not sure what I was looking at that made me think that.

Sorry about that :)
