### ISSUE TITLE
Requesting License information for control_msgs

### ISSUE THREAD

**Issue by jsubramo** [ros-controls/control_msgs#92]
Hi, 

Can I know the license under which I can use this control_msgs,

Thanks,

**Comment by bmagyar** [comment]
Which release? I suggest checking the appropriate branch for the Ros distro and consulting the package.xml

**Comment by jsubramo** [comment]
Hello, 
Thanks for your reply, 
Reg. control_msgs, I am using master branch.
My development is in humble ROS2 version. Can you pl let me know if I can control_msgs master branch for Humble ROS2, 

It would be really useful if you can help me with the links to look for the license, 
Thanks again,

**Comment by christophfroehlich** [comment]
@jsubramo have a look in the table in the README, `humble` branch is the correct one for humble ROS 2 distro. There you find the [LICENSE](https://github.com/ros-controls/control_msgs/blob/humble/LICENSE) file, or also the [package.xml](https://github.com/ros-controls/control_msgs/blob/humble/control_msgs/package.xml). You can also consult [index.ros.org](https://index.ros.org/p/control_msgs/github-ros-controls-control_msgs/#humble) for answering such questions.
